[package]
name = "ARMecha-Firmware"
version = "0.1.0"
authors = ["Paul_GD <PaulGameDev@GitHub>", "ARMecha <ARMecha@GitHub>"]
edition = "2021"
description = "A keyboard firmware written in Rust and C++ made specifically for ARM chips, aiming to natively support SONiX / eVision chips too!"
repository = "https://github.com/ARMecha/ARMecha-Firmware"
keywords = ["keyboard", "usb-device", "firmare"]
categories = ["embedded", "no-std"]
license = "GPLv3"
readme = "README.md"

[dependecies]
keyberon-macros = { version = "0.1.0", path = "./keyberon-macros" }
either = { version = "1.6", default-features = false }
generic-array = "0.14"
embedded-hal = { version = "0.2", features = ["unproven"] }
usb-device = "0.2.0"
heapless = "0.5"
arraydeque = { version = "0.4.5", default-features = false }