[general]
name = "BMMP TKL ISO"
author = "Paul_GD"
device = 0x0001
vid = 0xDEAD
pid = 0xBEEF

[pins]
rows = ["PA3", "PA2", "PA1", "PB9", "PB8", "PB4", "PB3", "PA15", "PA10", "PA8", "PB15", "PB14", "PB13"]
cols = ["PB10", "PB1", "PB0", "PA7", "PA6", "PA5", "PA4"]
diode_dir = "ROW2COL"

[mcu]
manufacturer = "STMicroelectronics"
family = "STM32F4xx"
flash = "512K"
ram = "128K"

[dynamic_keymap]
enable = "yes"