[general]
name = "BMMP TKL ISO"
author = "Paul_GD"
device = 0x0001
vid = 0xDEAD
pid = 0xBEEF

[pins]
rows = ["A3", "A2", "A1", "B9", "B8", "B4", "B3", "A15", "A10", "A8", "B15", "B14", "B13"]
cols = ["B10", "B1", "B0", "A7", "A6", "A5", "A4"]
diode_dir = "ROW2COL"

[mcu]
manufacturer = "STMicroelectronics"
family = "STM32F4xx"
flash = "512K"
ram = "128K"

[dynamic_keymap]
enable = true 