[general]
name = "GMMK TKL ISO"
author = "Glorious PC Gaming Race"
device = "0x0001"
vid = "0xDEAD"
pid = "0xBEEF"

[pins]
rows = ["A3", "A2", "A1", "B9", "B8", "B4", "B3", "A15", "A10", "A8", "B15", "B14", "B13"]
cols = ["B10", "B1", "B0", "A7", "A6", "A5", "A4"]
diode_dir = "ROW2COL"

[mcu]
manufacturer = "SONiX"
family = "SN32F26x"
rom = "32K"
ram = "2K"

[dynamic_keymap]
emulated_eeprom = false